#!/usr/bin/with-contenv bash

# create custom folders and secure permissions
mkdir -p /home/cuong/config/{custom-cont-init.d,custom-services.d}
chown -R 0:0 /home/cuong/config/{custom-cont-init.d,custom-services.d}
